FROM python:3.12-slim

WORKDIR /app

COPY ./backend /app/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3000

CMD sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py setup_admin && python manage.py runserver 0.0.0.0:3000"
