FROM node:16-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /app

COPY ./frontend/package.json ./frontend/package-lock.json* ./

RUN npm ci

COPY ./frontend .
RUN chown -R appuser:appgroup /app

USER appuser

ENV REACT_APP_BACKEND_URL=/api
ENV DOCKER_ENV=true
ENV PORT=3002

RUN npm run build

EXPOSE 3002

CMD npm start