FROM node:16-alpine

WORKDIR /app

COPY ./frontend/package.json ./frontend/package-lock.json* ./

RUN npm install

COPY ./frontend .

ENV REACT_APP_BACKEND_URL=http://backend:3000
ENV DOCKER_ENV=true
ENV PORT=3002

RUN npm run build

EXPOSE 3002

CMD npm start