FROM python:3.12-slim
WORKDIR /app
COPY ./backend /app/
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 3000
RUN apt-get update && apt-get install -y netcat-openbsd
RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
