# Generated by Django 5.0.7 on 2024-08-05 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('words', models.TextField()),
                ('match_method', models.CharField(choices=[('all', 'All words'), ('any', 'Any word'), ('exact', 'Exact phrase')], max_length=10)),
                ('label', models.CharField(blank=True, choices=[('Person', 'Person:'), ('Category', 'Category:'), ('Location', 'Location:'), ('Amount', 'Amount:'), ('Date', 'Date:'), ('Other', 'Other:')], max_length=20, null=True)),
                ('metadata_key', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_type', models.CharField(blank=True, choices=[('next_n_words', 'Next N Words'), ('regex', 'Regular Expression'), ('string_match', 'String Match')], max_length=20, null=True)),
                ('metadata_value', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_tag', models.BooleanField(default=True, help_text='Automatically tag transactions with this label')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.tag')),
            ],
            options={
                'verbose_name_plural': 'Admin Rules',
            },
        ),
        migrations.CreateModel(
            name='CustomRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('words', models.TextField()),
                ('match_method', models.CharField(choices=[('all', 'All words'), ('any', 'Any word'), ('exact', 'Exact phrase')], max_length=10)),
                ('label', models.CharField(blank=True, choices=[('Person', 'Person:'), ('Category', 'Category:'), ('Location', 'Location:'), ('Amount', 'Amount:'), ('Date', 'Date:'), ('Other', 'Other:')], max_length=20, null=True)),
                ('metadata_key', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_type', models.CharField(blank=True, choices=[('next_n_words', 'Next N Words'), ('regex', 'Regular Expression'), ('string_match', 'String Match')], max_length=20, null=True)),
                ('metadata_value', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_tag', models.BooleanField(default=True, help_text='Automatically tag transactions with this label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.tag')),
            ],
            options={
                'verbose_name_plural': 'Custom Rules',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=6)),
                ('posting_date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('check_or_slip', models.CharField(blank=True, max_length=100, null=True)),
                ('structured_tags', models.JSONField(blank=True, default=dict)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('tags', models.ManyToManyField(blank=True, to='storage.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'details', 'posting_date', 'description', 'amount', 'transaction_type', 'balance', 'check_or_slip')},
            },
        ),
    ]
