# Generated by Django 5.0.7 on 2024-07-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_tag_alter_transaction_posting_date_transaction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parsed_description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
