# Generated by Django 5.0.6 on 2024-06-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('details', 'posting_date', 'description', 'amount', 'transaction_type', 'balance', 'check_or_slip')},
        ),
    ]
