# Generated by Django 5.0.7 on 2024-07-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_transaction_category_transaction_parsed_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='parsed_description',
        ),
    ]
