# Generated by Django 5.0.7 on 2024-07-31 11:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_transaction_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('user', 'details', 'posting_date', 'description', 'amount', 'transaction_type', 'balance', 'check_or_slip')},
        ),
    ]
